extends:
  - airbnb
  - plugin:flowtype/recommended
parser: babel-eslint
plugins:
  - flowtype
rules:
  semi: [warn, never]
  no-use-before-define: [warn, 'nofunc']
  react/sort-comp: [warn, {
    order: [
      type-annotations
      static-methods
      lifecycle
      everything-else
      render
    ]
  }]
  no-cond-assign: [error, except-parens]
  max-len: [error, 120]
