// flow-typed signature: c57111bd2c6fa3c505bf8f62be25673f
// flow-typed version: <<STUB>>/draft-js-typeahead_v^0.1.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-typeahead'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-typeahead' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-typeahead/dist/draft-typeahead' {
  declare module.exports: any;
}

declare module 'draft-js-typeahead/dist/draft-typeahead.min' {
  declare module.exports: any;
}

declare module 'draft-js-typeahead/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-typeahead/dist/draft-typeahead.js' {
  declare module.exports: $Exports<'draft-js-typeahead/dist/draft-typeahead'>;
}
declare module 'draft-js-typeahead/dist/draft-typeahead.min.js' {
  declare module.exports: $Exports<'draft-js-typeahead/dist/draft-typeahead.min'>;
}
declare module 'draft-js-typeahead/lib/index.js' {
  declare module.exports: $Exports<'draft-js-typeahead/lib/index'>;
}
