// flow-typed signature: d647b3484aafab8491adf301f95243db
// flow-typed version: <<STUB>>/react-stamp_v^0.6.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-stamp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-stamp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-stamp/dist/react-stamp' {
  declare module.exports: any;
}

declare module 'react-stamp/dist/react-stamp.min' {
  declare module.exports: any;
}

declare module 'react-stamp/lib/index' {
  declare module.exports: any;
}

declare module 'react-stamp/lib/utils/compose' {
  declare module.exports: any;
}

declare module 'react-stamp/lib/utils/descriptor' {
  declare module.exports: any;
}

declare module 'react-stamp/lib/utils/index' {
  declare module.exports: any;
}

declare module 'react-stamp/lib/utils/react' {
  declare module.exports: any;
}

declare module 'react-stamp/src/index' {
  declare module.exports: any;
}

declare module 'react-stamp/src/utils/compose' {
  declare module.exports: any;
}

declare module 'react-stamp/src/utils/descriptor' {
  declare module.exports: any;
}

declare module 'react-stamp/src/utils/index' {
  declare module.exports: any;
}

declare module 'react-stamp/src/utils/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-stamp/dist/react-stamp.js' {
  declare module.exports: $Exports<'react-stamp/dist/react-stamp'>;
}
declare module 'react-stamp/dist/react-stamp.min.js' {
  declare module.exports: $Exports<'react-stamp/dist/react-stamp.min'>;
}
declare module 'react-stamp/lib/index.js' {
  declare module.exports: $Exports<'react-stamp/lib/index'>;
}
declare module 'react-stamp/lib/utils/compose.js' {
  declare module.exports: $Exports<'react-stamp/lib/utils/compose'>;
}
declare module 'react-stamp/lib/utils/descriptor.js' {
  declare module.exports: $Exports<'react-stamp/lib/utils/descriptor'>;
}
declare module 'react-stamp/lib/utils/index.js' {
  declare module.exports: $Exports<'react-stamp/lib/utils/index'>;
}
declare module 'react-stamp/lib/utils/react.js' {
  declare module.exports: $Exports<'react-stamp/lib/utils/react'>;
}
declare module 'react-stamp/src/index.js' {
  declare module.exports: $Exports<'react-stamp/src/index'>;
}
declare module 'react-stamp/src/utils/compose.js' {
  declare module.exports: $Exports<'react-stamp/src/utils/compose'>;
}
declare module 'react-stamp/src/utils/descriptor.js' {
  declare module.exports: $Exports<'react-stamp/src/utils/descriptor'>;
}
declare module 'react-stamp/src/utils/index.js' {
  declare module.exports: $Exports<'react-stamp/src/utils/index'>;
}
declare module 'react-stamp/src/utils/react.js' {
  declare module.exports: $Exports<'react-stamp/src/utils/react'>;
}
